const PLAN={className:'1P',validFrom:'27.04.2026',source:'https://zsmeie.torun.pl/plan/#1P',days:{
1:[['08:00','08:45','Religia','RK','77'],['08:50','09:35','Matematyka','jK','71'],['09:45','10:30','j.niemiecki','ND','77','Informatyka','PA','19'],['10:35','11:20','p_pr_ad_bd','Po','18','Informatyka','PA','19'],['11:30','12:15','p_pr_ad_bd','Po','18','p_adm_lo_s_k','SM','7p'],['13:25','14:10','t_sys_op','BO','74','p_adm_lo_s_k','SM','7p']],
2:[['08:00','08:45','t_pod_info','BO','71'],['08:50','09:35','t_pr_ad_bd.','Po','23'],['09:45','10:30','t_pr_ad_bd.','Po','23','j.niemiecki','Sz','42a'],['10:35','11:20','chemia','Sa','64','j.angielski','SN','25'],['11:30','12:15','Matematyka','jK','71','p_adm_lo_s_k','SM','7p'],['13:25','14:10','p_sys_op','BO','8p','Informatyka','BO','70'],['14:30','15:15','p_sys_op','BO','8p']],
3:[['08:00','08:45','j.polski','BW','77'],['08:50','09:35','geografia','LM','54'],['09:45','10:30','WF','AP','s4','WF','PJ','s2'],['10:35','11:20','j.angielski','SR','6i','p_pr_i_tw_st','KC','18'],['11:30','12:15','historia','BL','68'],['13:25','14:10','historia','BL','68'],['14:30','15:15','j.angielski','IK','12p'],['15:25','16:10','bizn.i zarz.','SG','74']],
4:[['08:50','09:35','E.zdr','RM','64'],['09:45','10:30','bizn.i zarz.','SG','25','WF','PJ','s2'],['10:35','11:20','WF','AP','s1','p_pr_i_tw_st','KC','18'],['11:30','12:15','WF','AP','s1','Matematyka','jK','71'],['13:25','14:10','p_utk','PS','8p'],['14:30','15:15','p_utk','PS','8p','Informatyka','BO','70'],['15:25','16:10','religia','RK','71']],
5:[['08:00','08:45','j.polski','BW','77'],['08:50','09:35','j.polski','BW','77'],['09:45','10:30','j.niemiecki','ND','42b','j.niemiecki','Sz','42a'],['10:35','11:20','j.angielski','SR','6i','WF','PJ','s2'],['11:30','12:15','Matematyka','jK','71'],['13:25','14:10','fizyka','SC','57'],['15:25','16:10','p_utk','PS','8p']]
}};
const timesToMin=s=>{const[a,b]=s.split(':').map(Number);return a*60+b};
const fmtMin=n=>{n=Math.max(0,n);return `${n} min`};
const dayNum=()=>new Date().getDay();
const getRaw=(arr,i)=>arr.length>=8?{start:arr[0],end:arr[1],a:{name:arr[2],teacher:arr[3],room:arr[4],group:1},b:{name:arr[5],teacher:arr[6],room:arr[7],group:2}}:{start:arr[0],end:arr[1],a:{name:arr[2],teacher:arr[3],room:arr[4]}};
const $=id=>document.getElementById(id);
let settings=JSON.parse(localStorage.getItem('aestroSettings')||'null')||{group:1,showTeacher:true,showRoom:true,showBothGroups:true,darkMode:true,fiveMin:true};
let reminded={};
function save(){localStorage.setItem('aestroSettings',JSON.stringify(settings))}
function subjectText(s){if(!s)return '—';let bits=[settings.showTeacher&&s.teacher,settings.showRoom&&s.room].filter(Boolean);return bits.join(' · ')}
function selectedSubject(slot){return slot.b ? (settings.group===1?slot.a:slot.b):slot.a}
function dayLessons(d=dayNum()){return PLAN.days[d]||[]}
function nextAndState(){const now=new Date();const mins=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;const lessons=dayLessons();let current=null,next=null;for(const raw of lessons){const s=getRaw(raw);if(mins>=timesToMin(s.start)&&mins<timesToMin(s.end)){current=s;break}if(mins<timesToMin(s.start)){next=s;break}}let breakInfo=null;if(!current){const prior=lessons.filter(r=>timesToMin(getRaw(r).end)<=mins).map(getRaw).at(-1);const upcoming=next;if(prior&&upcoming){const st=timesToMin(prior.end),en=timesToMin(upcoming.start);if(en>st)breakInfo={start:st,end:en,length:en-st,remaining:Math.max(0,Math.ceil(en-mins))}}}return{mins,current,next,breakInfo,lessons}}
function render(){const now=new Date();$('clock').textContent=now.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'});$('dateLine').textContent=now.toLocaleDateString('pl-PL',{weekday:'long',day:'numeric',month:'long'});const {mins,current,next,breakInfo,lessons}=nextAndState();let state='';if(current){state='LEKCJA';$('statePill').textContent='● TERAZ';const subj=selectedSubject(current);$('currentTitle').textContent=subj.name;$('currentMeta').textContent=subjectText(subj);const end=timesToMin(current.end),start=timesToMin(current.start);const left=Math.max(0,Math.ceil(end-mins));$('timeText').textContent=left+' min';$('timeCaption').textContent='do końca';$('progressBar').style.width=Math.min(100,Math.max(0,((mins-start)/(end-start))*100))+'%';if(current.b&&settings.showBothGroups){$('currentMeta').textContent=`G1: ${current.a.name} · ${subjectText(current.a)}  |  G2: ${current.b.name} · ${subjectText(current.b)}`}}else if(breakInfo){state='PRZERWA';$('statePill').textContent='PRZERWA';$('currentTitle').textContent='Masz przerwę';$('currentMeta').textContent=`Następna: ${selectedSubject(next)?.name||'—'} · ${next?.start||''}`;$('timeText').textContent=breakInfo.remaining+' min';$('timeCaption').textContent='przerwy zostało';$('progressBar').style.width=Math.min(100,Math.max(0,((mins-breakInfo.start)/breakInfo.length)*100))+'%'}else if(next){state='PRZED LEKCJĄ';$('statePill').textContent='NASTĘPNA';$('currentTitle').textContent=selectedSubject(next)?.name||'—';$('currentMeta').textContent=subjectText(selectedSubject(next));$('timeText').textContent=Math.max(0,Math.ceil(timesToMin(next.start)-mins))+' min';$('timeCaption').textContent='do lekcji';$('progressBar').style.width='0%'}else{state='KONIEC';$('statePill').textContent='KONIEC';$('currentTitle').textContent='Koniec zajęć';$('currentMeta').textContent='Na dziś nie ma już lekcji.';$('timeText').textContent='';$('timeCaption').textContent='';$('progressBar').style.width='100%'}
$('nextTitle').textContent=next?selectedSubject(next)?.name||'—':'—';$('nextMeta').textContent=next?`${next.start}–${next.end} · ${subjectText(selectedSubject(next))}`:'Brak kolejnej lekcji';
if(breakInfo){$('breakText').textContent=breakInfo.length+' min';$('breakMeta').textContent=`Pozostało ${breakInfo.remaining} min`}else{$('breakText').textContent='—';$('breakMeta').textContent='Poza przerwą'}
const list=$('scheduleList');list.innerHTML='';for(const raw of lessons){const s=getRaw(raw);const active=current&&s.start===current.start&&s.end===current.end;const done=mins>=timesToMin(s.end);const sub=selectedSubject(s);const el=document.createElement('div');el.className='lesson '+(active?'active ':'')+(done?'dim':'');el.innerHTML=`<div class="lesson-time">${s.start}<br>${s.end}</div><div><div class="lesson-name">${sub.name}</div><div class="lesson-meta">${subjectText(sub)}</div>${s.b&&settings.showBothGroups?`<div class="groups"><div class="group-line"><b>G1</b> · ${s.a.name} · ${subjectText(s.a)}</div><div class="group-line"><b>G2</b> · ${s.b.name} · ${subjectText(s.b)}</div></div>`:''}</div><div class="badge">${active?'TERAZ':done?'DONE':s.start}</div>`;list.appendChild(el)}
if(current&&settings.fiveMin){const left=timesToMin(current.end)-mins;if(left<=5&&left>0){const key=new Date().toISOString().slice(0,10)+'_'+current.start;if(!reminded[key]){reminded[key]=true;showToast(`⏰ ${selectedSubject(current).name} — 5 min do końca`);try{navigator.vibrate?.([120,70,120])}catch{}}}}
}
function showToast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3500)}
function initSettings(){ $('groupSelect').value=settings.group;$('showTeacher').checked=settings.showTeacher;$('showRoom').checked=settings.showRoom;$('showBothGroups').checked=settings.showBothGroups;$('darkMode').checked=settings.darkMode;$('fiveMin').checked=settings.fiveMin}
function bind(){ $('settingsBtn').onclick=()=>{$('settingsModal').classList.remove('hidden');initSettings()}; $('closeSettings').onclick=()=>$('settingsModal').classList.add('hidden'); $('modalBackdrop').onclick=()=>$('settingsModal').classList.add('hidden');
[['groupSelect','group',v=>Number(v)],['showTeacher','showTeacher',v=>v],['showRoom','showRoom',v=>v],['showBothGroups','showBothGroups',v=>v],['darkMode','darkMode',v=>v],['fiveMin','fiveMin',v=>v]].forEach(([id,key,cast])=>$(id).addEventListener('change',e=>{settings[key]=cast(e.target.type==='checkbox'?e.target.checked:e.target.value);save();render()}));
$('sourceBtn').onclick=()=>window.open(PLAN.source,'_blank');
$('notifyBtn').onclick=async()=>{if(!('Notification'in window)){showToast('Ta przeglądarka nie obsługuje powiadomień.');return}const p=await Notification.requestPermission();showToast(p==='granted'?'Powiadomienia włączone.':'Nie przyznano zgody.')};
}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
bind();render();setInterval(render,1000);
